// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SeaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sea() {
    // Test name: Sea
    // Step # | name | target | value
    // 1 | open | http://localhost:8080/MyTranslate/ | 
    driver.get("http://localhost:8080/MyTranslate/");
    // 2 | setWindowSize | 697x726 | 
    driver.manage().window().setSize(new Dimension(697, 726));
    // 3 | click | name=palavra | 
    driver.findElement(By.name("palavra")).click();
    // 4 | type | name=palavra | sEa
    driver.findElement(By.name("palavra")).sendKeys("sEa");
    // 5 | click | css=input:nth-child(3) | 
    driver.findElement(By.cssSelector("input:nth-child(3)")).click();
    // 6 | click | css=h1 | 
    driver.findElement(By.cssSelector("h1")).click();
    // 7 | click | css=h1 | 
    driver.findElement(By.cssSelector("h1")).click();
    // 8 | doubleClick | css=h1 | 
    {
      WebElement element = driver.findElement(By.cssSelector("h1"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    // 9 | assertText | css=h1 | Mar
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Mar"));
  }
}
